server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.postgresql.Driver
#
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pagamento
    username: microservices
    password: microservices123
